name: nicless_flutter
description: "Take control over Nicotine"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

#  # Local Dependencies
#  widgets:
#    path: module/widgets
#  core:
#    path: module/core


  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  # Firebase
  # firebase_core: ^2.15.1
  # firebase_crashlytics: ^3.4.4
  # firebase_analytics: ^10.7.0
  # firebase_performance: ^0.9.3+4
  # firebase_messaging: ^14.7.4
  # cloud_firestore: ^4.9.1
  # firebase_auth: ^4.9.0
  # google_sign_in: ^6.1.5

  # Core
  jose: ^0.3.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.18.1
  dartz: ^0.10.1
  get_it: ^7.6.4

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # Network
  dio: ^5.4.0

  # Picker
  file_picker: ^6.1.1
  image_picker: ^1.0.4

  # UI
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  device_preview: ^1.1.0
  fl_chart: ^0.66.0

  # Others
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  auto_route: ^7.8.4
  path_provider: ^2.1.1
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.0.1
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons: # flutter pub run flutter_launcher_icons
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/launcher.png"
#  min_sdk_android: 21
#  remove_alpha_ios: true

#dependency_overrides:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/svg/
    - assets/images/
