// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXQxGaeTmwWroN4QUeOGmvZgM-btoxlo',
    appId: '1:562901775042:web:1f89f6dde50176c3d9015b',
    messagingSenderId: '562901775042',
    projectId: 'nicless-flutter',
    authDomain: 'nicless-flutter.firebaseapp.com',
    storageBucket: 'nicless-flutter.appspot.com',
    measurementId: 'G-QZXSYTH9T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3I9_vTcVY8B0h2cBceu3hvmuAgHvoJgk',
    appId: '1:562901775042:android:72f26542e4621d3cd9015b',
    messagingSenderId: '562901775042',
    projectId: 'nicless-flutter',
    storageBucket: 'nicless-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKgeA26kE22BTQRw8ypYsyASjROpNCJE',
    appId: '1:562901775042:ios:eb59ca02d8bed2dcd9015b',
    messagingSenderId: '562901775042',
    projectId: 'nicless-flutter',
    storageBucket: 'nicless-flutter.appspot.com',
    iosBundleId: 'com.behzodfaiziev.niclessFlutter',
  );
}
