name: Dart

on:
  push:
    branches: [ "main","alpha" ]
  pull_request:
    branches: [ "main", "alpha" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0

      - name: Install dependencies
        run: flutter pub get
      # Analyze the project source
      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings

      # Run test to ensure that the code is working as expected
      - name: Run tests
        run: flutter test